// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu04wwRb1SI0cUICdXAN431mwNxBtiskc',
    appId: '1:228424488810:web:1be17573519ed6d956f713',
    messagingSenderId: '228424488810',
    projectId: 'chatapplication-18c35',
    authDomain: 'chatapplication-18c35.firebaseapp.com',
    storageBucket: 'chatapplication-18c35.firebasestorage.app',
    measurementId: 'G-NCPQJGM41L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0hdJSkMeQ1s6T9GJ-KWD9fBTFg5DWe7w',
    appId: '1:228424488810:android:345bbddf02e3b05656f713',
    messagingSenderId: '228424488810',
    projectId: 'chatapplication-18c35',
    storageBucket: 'chatapplication-18c35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1YFPA8yA_lKTw2E2Uxkcf2TGcZxO9AP0',
    appId: '1:228424488810:ios:3f35da7e9159f0df56f713',
    messagingSenderId: '228424488810',
    projectId: 'chatapplication-18c35',
    storageBucket: 'chatapplication-18c35.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1YFPA8yA_lKTw2E2Uxkcf2TGcZxO9AP0',
    appId: '1:228424488810:ios:3f35da7e9159f0df56f713',
    messagingSenderId: '228424488810',
    projectId: 'chatapplication-18c35',
    storageBucket: 'chatapplication-18c35.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu04wwRb1SI0cUICdXAN431mwNxBtiskc',
    appId: '1:228424488810:web:72c66ea1592d1b9e56f713',
    messagingSenderId: '228424488810',
    projectId: 'chatapplication-18c35',
    authDomain: 'chatapplication-18c35.firebaseapp.com',
    storageBucket: 'chatapplication-18c35.firebasestorage.app',
    measurementId: 'G-6L51BMYD6Z',
  );
}
